function simulationInput = create_simulation_input(paths, config, trajectory)
% create_simulation_input  外部軌道とsimulation設定をSimulationInputへ束ねる。

validateattributes(trajectory.time_s, {'numeric'}, {'column', 'real', 'finite'});
assert(isequal(size(trajectory.position_m), [numel(trajectory.time_s), 2]), ...
    'trajectory.position_m must be N-by-2.');
simulationInput = Simulink.SimulationInput(paths.systemModelName);
command = timeseries(trajectory.position_m, trajectory.time_s, ...
    "Name", "command_xy_m");
simulationInput = simulationInput.setExternalInput(command);
simulationInput = simulationInput.setModelParameter( ...
    "StopTime", string(trajectory.time_s(end)), ...
    "Solver", string(config.simulation.solver), ...
    "FixedStep", string(config.simulation.fixed_step));
simulationInput = simulationInput.setVariable("time_constant_s", config.plant.time_constant, ...
    Workspace=paths.systemModelName);
end
