function paths = model_paths(projectRoot)
% model_paths  Simulink model artifactsの絶対パスを返す。

if nargin < 1 || strlength(string(projectRoot)) == 0
    projectRoot = fileparts(fileparts(fileparts(fileparts(mfilename("fullpath")))));
end
projectRoot = char(string(projectRoot));
paths = struct( ...
    "projectRoot", projectRoot, ...
    "plantDirectory", fullfile(projectRoot, 'models', 'plant'), ...
    "systemDirectory", fullfile(projectRoot, 'models', 'system'), ...
    "plant", fullfile(projectRoot, 'models', 'plant', 'first_order_2d.slx'), ...
    "system", fullfile(projectRoot, 'models', 'system', 'teleop_delay_system.slx'), ...
    "plantModelName", 'first_order_2d', ...
    "systemModelName", 'teleop_delay_system');
end
