function simulation = run_case(simulationInput, paths, config)
% run_case  headless simulationを実行し、logging結果を共通schemaへ変換する。

load_system(paths.plant);
load_system(paths.communication);
load_system(paths.system);
cleanup = onCleanup(@() close_models(paths));
set_param(paths.systemModelName, "SimulationCommand", "update");
simulationOutput = sim(simulationInput);
loggedOutputs = simulationOutput.yout;
elementNames = cellstr(loggedOutputs.getElementNames());
teleopdelay.simulink.validate_logging_names(elementNames);
values = struct();
names = ["zoh_command_xy_m", "cv_command_xy_m", "zoh_position_xy_m", ...
    "cv_position_xy_m", "reference_position_xy_m", "packet_timestamp_s", ...
    "packet_age_s", "packet_valid"];
for name = names
    values.(char(name)) = loggedOutputs.getElement(char(name)).Values;
end
simulation = struct( ...
    "time_s", values.zoh_command_xy_m.Time, ...
    "zoh_command_xy_m", normalize_xy(values.zoh_command_xy_m.Data), ...
    "cv_command_xy_m", normalize_xy(values.cv_command_xy_m.Data), ...
    "zoh_position_xy_m", normalize_xy(values.zoh_position_xy_m.Data), ...
    "cv_position_xy_m", normalize_xy(values.cv_position_xy_m.Data), ...
    "reference_position_xy_m", normalize_xy(values.reference_position_xy_m.Data), ...
    "packet_timestamp_s", values.packet_timestamp_s.Data, ...
    "packet_age_s", values.packet_age_s.Data, ...
    "packet_valid", logical(values.packet_valid.Data), ...
    "solver", string(config.simulation.solver), ...
    "fixed_step_s", config.simulation.fixed_step);
assert(isequal(size(simulation.time_s, 2), 1), 'simulation.time_s must be a column.');
assert(isequal(size(simulation.zoh_command_xy_m), [numel(simulation.time_s), 2]), ...
    'simulation.zoh_command_xy_m must be N-by-2.');
assert(isequal(size(simulation.cv_command_xy_m), [numel(simulation.time_s), 2]), ...
    'simulation.cv_command_xy_m must be N-by-2.');
assert(isequal(size(simulation.zoh_position_xy_m), [numel(simulation.time_s), 2]), ...
    'simulation.zoh_position_xy_m must be N-by-2.');
assert(isequal(size(simulation.cv_position_xy_m), [numel(simulation.time_s), 2]), ...
    'simulation plant output must be N-by-2.');
assert(isequal(size(simulation.reference_position_xy_m), [numel(simulation.time_s), 2]), ...
    'simulation reference output must be N-by-2.');
assert(isequal(size(simulation.packet_timestamp_s), [numel(simulation.time_s), 1]) && ...
    isequal(size(simulation.packet_age_s), [numel(simulation.time_s), 1]) && ...
    isequal(size(simulation.packet_valid), [numel(simulation.time_s), 1]), ...
    'packet diagnostics must be N-by-1.');
assert(all(isfinite(simulation.zoh_command_xy_m), "all") && ...
    all(isfinite(simulation.cv_command_xy_m), "all") && ...
    all(isfinite(simulation.zoh_position_xy_m), "all") && ...
    all(isfinite(simulation.reference_position_xy_m), "all") && ...
    all(isfinite(simulation.cv_position_xy_m), "all") && ...
    all(isfinite(simulation.packet_timestamp_s)) && all(isfinite(simulation.packet_age_s)), ...
    'simulation output must be finite.');
clear cleanup;
close_if_loaded(paths.systemModelName);
close_if_loaded(paths.communicationModelName);
close_if_loaded(paths.plantModelName);
end

function value = normalize_xy(value)
if ndims(value) == 3 && size(value, 1) == 1 && size(value, 2) == 2
    value = reshape(value, 2, []).';
end
end

function close_models(paths)
close_if_loaded(paths.systemModelName);
close_if_loaded(paths.communicationModelName);
close_if_loaded(paths.plantModelName);
end

function close_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
