function analysisId = analysis_id(input, config, toleranceContract, convergence)
% analysis_id  Deterministic identifier excluding timestamps and run folders.

identity = struct( ...
    "experiment_id", string(input.source_experiment_id), ...
    "input_sha256", string(input.source_mat_sha256), ...
    "analysis_schema_version", string(config.analysis_schema_version), ...
    "analysis_config", config, ...
    "boundary_tolerance_contract", toleranceContract, ...
    "convergence_config", config.convergence, ...
    "convergence_available", logical(convergence.available));
text = jsonencode(identity);
digest = teleopdelay.analysis.sha256_text(text);
analysisId = "i9v1_" + string(input.source_experiment_id) + "_" + extractBefore(digest, 13);
end
