function tableValue = convergence_table(rows)
% convergence_table  Stable schema for the supplementary convergence result.

names = {'role', 'role_mapping', 'trajectory', 'case_id', 'omega_rad_s', 'delay_s', ...
    'base_fixed_step_s', 'refined_fixed_step_s', 'sample_period_s', 'base_rmse_zoh_m', ...
    'refined_rmse_zoh_m', 'base_rmse_cv_m', 'refined_rmse_cv_m', 'base_performance_ratio', ...
    'refined_performance_ratio', 'delta_rmse_zoh_m', 'delta_rmse_cv_m', ...
    'delta_performance_ratio', 'relative_delta_rmse_zoh', 'relative_delta_rmse_cv', ...
    'relative_delta_performance_ratio', 'base_max_error_zoh_m', 'refined_max_error_zoh_m', ...
    'base_max_error_cv_m', 'refined_max_error_cv_m', 'delta_max_error_zoh_m', ...
    'delta_max_error_cv_m', 'sample_alignment_ratio', 'sample_alignment_valid', ...
    'convergence_status'};
if nargin == 0 || isempty(rows)
    tableValue = table('Size', [0, numel(names)], 'VariableTypes', ...
        ["string", "string", "string", "string", repmat("double", 1, 24), "logical", "string"], ...
        'VariableNames', names);
else
    tableValue = cell2table(rows, "VariableNames", names);
    for name = names(5:end-2)
        tableValue.(char(name)) = double(tableValue.(char(name)));
    end
    tableValue.sample_alignment_valid = logical(tableValue.sample_alignment_valid);
end
end
