function config = default_config()
% default_config  Fixed Issue #9 analysis contract.

config = struct( ...
    "analysis_schema_version", "issue9.analysis.v1", ...
    "classification_safety_factor", 4.0, ...
    "machine_precision_multiplier", 32.0, ...
    "event_acceleration_percentile", 75.0, ...
    "near_collinearity_condition_limit", 1e10, ...
    "figure_dpi", 300, ...
    "theoretical_candidate_definition", ...
        "First positive nonzero root of q = 2 sin(q) for ideal sinusoid ZOH/CV error equality.", ...
    "theoretical_candidate_source", ...
        "Analytic derivation in Issue #9 implementation; no repository literature source was found.", ...
    "convergence", struct( ...
        "schema_version", "issue9.convergence.v1", ...
        "base_fixed_step_s", 0.005, ...
        "refined_fixed_step_s", 0.0025, ...
        "sample_period_s", 0.020, ...
        "solver", "ode4", ...
        "alignment_tolerance", 128 * eps(1.0)));
end
