function contract = event_display_contract()
% event_display_contract  Define the non-causal event rendering contract.

contract = struct( ...
    "upper_mode", "shared-rug", ...
    "upper_label", "高加速度時刻", ...
    "lower_label", "高加速度時刻", ...
    "note", "高加速度時刻との対応は時間的一致のみを示し、因果関係を意味しない。", ...
    "percentile_label", "75パーセンタイル閾値");
end
