function input = load_input(inputMat)
% load_input  Load and fail-closed validate an explicit Issue #8 MAT file.

inputMat = string(inputMat);
if strlength(inputMat) == 0 || ~isfile(inputMat)
    error("teleopDelay:AnalysisInputMissing", ...
        "The explicit InputMat does not exist: %s", inputMat);
end
inputMat = string(char(java.io.File(char(inputMat)).getCanonicalPath()));
sourceSha256 = teleopdelay.experiment.sha256_file(inputMat);
try
    loaded = load(inputMat, "manifest", "aggregate", "metadata", "cases", ...
        "run_status", "experiment_id", "run_id");
catch exception
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Could not load the required Issue #8 MAT fields [%s]: %s", ...
        exception.identifier, exception.message);
end
required = ["manifest", "aggregate", "metadata", "cases", "run_status", ...
    "experiment_id", "run_id"];
if ~all(isfield(loaded, required))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input MAT is missing one or more required top-level fields.");
end
validate_input_fields(loaded);
input = loaded;
input.source_mat = inputMat;
input.source_mat_sha256 = string(sourceSha256);
input.source_experiment_id = string(loaded.experiment_id);
input.source_run_id = string(loaded.run_id);
end

function validate_input_fields(data)
if string(data.run_status) ~= "complete" || string(data.metadata.run_status) ~= "complete"
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input MAT must have run_status=complete.");
end
if ~isscalar(data.metadata) || ~all(isfield(data.metadata, ...
        ["success_case_count", "failed_case_count", "total_case_count"]))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input metadata is missing case-count fields.");
end
if data.metadata.success_case_count ~= 40 || data.metadata.failed_case_count ~= 0 || ...
        data.metadata.total_case_count ~= 40
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input metadata does not report exactly 40 successful cases.");
end
if ~istable(data.aggregate) || height(data.aggregate) ~= 40
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input aggregate must contain exactly 40 rows.");
end
if ~isscalar(data.manifest) || data.manifest.case_count ~= 40
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input manifest must describe exactly 40 cases.");
end
if ~iscell(data.cases) || numel(data.cases) ~= 40
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input cases must be a 40-element cell array.");
end
requiredAggregate = ["case_id", "trajectory", "omega_rad_s", "delay_s", ...
    "sample_period_s", "time_constant_s", "fixed_step_s", "duration_s", ...
    "warmup_cycles", "evaluation_start_s", "evaluation_end_s", "omega_delay", ...
    "mean_packet_age_s", "omega_mean_packet_age", "omega_time_constant", ...
    "omega_sample_period", "rmse_zoh_m", "rmse_cv_m", "nrmse_zoh", ...
    "nrmse_cv", "max_error_zoh_m", "max_error_cv_m", "performance_ratio", ...
    "improvement_percent", "status"];
if ~all(ismember(requiredAggregate, string(data.aggregate.Properties.VariableNames)))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input aggregate is missing required columns.");
end
aggregateIds = string(data.aggregate.case_id);
if numel(unique(aggregateIds)) ~= 40 || any(strlength(aggregateIds) == 0)
    error("teleopDelay:AnalysisInputDuplicateCase", ...
        "Input aggregate contains duplicate or empty case_id values.");
end
if any(string(data.aggregate.status) ~= "success")
    error("teleopDelay:AnalysisInputIncomplete", ...
        "All aggregate rows must have status=success.");
end
requiredTrajectories = ["circle", "lissajous_1_2"];
if any(arrayfun(@(name) sum(string(data.aggregate.trajectory) == name) ~= 20, ...
        requiredTrajectories))
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Each trajectory must have exactly 20 rows.");
end
delays = sort(unique(double(data.aggregate.delay_s))).';
omegas = sort(unique(double(data.aggregate.omega_rad_s))).';
if ~isequal(delays, [0, 0.10, 0.20, 0.40, 0.50]) || ...
        ~isequal(omegas, [0.5, 1.0, 2.0, 4.0])
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input delay or omega grid does not match the Issue #8 standard grid.");
end
if any(arrayfun(@(delay) sum(double(data.aggregate.delay_s) == delay) ~= 8, delays)) || ...
        any(arrayfun(@(omega) sum(double(data.aggregate.omega_rad_s) == omega) ~= 10, omegas))
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input delay/omega marginal counts do not match the 40-case design.");
end
numericNames = required_numeric_columns();
numericValues = zeros(height(data.aggregate), numel(numericNames));
for numericIndex = 1:numel(numericNames)
    numericValues(:, numericIndex) = double(data.aggregate.(numericNames{numericIndex}));
end
if any(~isfinite(numericValues), "all")
    error("teleopDelay:AnalysisInputMetricInvalid", ...
        "Input aggregate contains a nonfinite required numeric value.");
end
conditionKeys = strings(40, 1);
for index = 1:40
    conditionKeys(index) = condition_key(data.aggregate(index, :));
end
if numel(unique(conditionKeys)) ~= 40
    error("teleopDelay:AnalysisInputDuplicateCase", ...
        "Input aggregate contains duplicate experimental conditions.");
end
for index = 1:40
    caseResult = data.cases{index};
    if ~isstruct(caseResult) || ~isscalar(caseResult) || ...
            ~all(isfield(caseResult, ["case_id", "status", "config", "trajectory", ...
            "simulation", "evaluation"]))
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "Case %d is missing the required result schema.", index);
    end
    if string(caseResult.status) ~= "success"
        error("teleopDelay:AnalysisInputIncomplete", ...
            "All MAT cases must have status=success.");
    end
    if ~ismember(string(caseResult.case_id), aggregateIds)
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "MAT case_id does not occur in aggregate: %s", string(caseResult.case_id));
    end
    aggregateIndex = find(aggregateIds == string(caseResult.case_id), 1);
    validate_case(caseResult, data.aggregate(aggregateIndex, :), index);
end
caseIds = strings(40, 1);
for index = 1:40
    caseIds(index) = string(data.cases{index}.case_id);
end
if numel(unique(caseIds)) ~= 40 || ~isequal(sort(caseIds), sort(aggregateIds))
    error("teleopDelay:AnalysisInputDuplicateCase", ...
        "MAT cases must have unique case_id values matching aggregate.");
end
end

function names = required_numeric_columns()
names = {"omega_rad_s", "delay_s", "sample_period_s", "time_constant_s", ...
    "fixed_step_s", "duration_s", "warmup_cycles", "evaluation_start_s", ...
    "evaluation_end_s", "omega_delay", "mean_packet_age_s", ...
    "omega_mean_packet_age", "omega_time_constant", "omega_sample_period", ...
    "rmse_zoh_m", "rmse_cv_m", "nrmse_zoh", "nrmse_cv", ...
    "max_error_zoh_m", "max_error_cv_m", "performance_ratio", ...
    "improvement_percent"};
end

function key = condition_key(row)
key = string(strjoin([string(row.trajectory), ...
    compose("%.17g", double(row.omega_rad_s)), ...
    compose("%.17g", double(row.delay_s)), ...
    compose("%.17g", double(row.sample_period_s)), ...
    compose("%.17g", double(row.time_constant_s)), ...
    compose("%.17g", double(row.fixed_step_s))], "|"));
end

function validate_case(caseResult, row, index)
config = caseResult.config;
if ~isstruct(config) || ~all(isfield(config, ["trajectory", "communication", "plant", "simulation", "evaluation"])) || ...
        ~all(isfield(config.trajectory, ["type", "amplitude", "omega"])) || ...
        ~all(isfield(config.communication, ["delay", "sample_period"])) || ...
        ~all(isfield(config.plant, "time_constant")) || ...
        ~all(isfield(config.simulation, ["dt", "fixed_step", "duration", "solver"])) || ...
        ~all(isfield(config.evaluation, ["total_cycles", "warmup_cycles"]))
    error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d config is incomplete.", index);
end
if ~isstruct(caseResult.trajectory) || ~all(isfield(caseResult.trajectory, ...
        ["time_s", "position_m", "velocity_mps", "acceleration_mps2"]))
    error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d trajectory is incomplete.", index);
end
simulation = caseResult.simulation;
evaluation = caseResult.evaluation;
simulationFields = ["time_s", "zoh_command_xy_m", "cv_command_xy_m", ...
    "zoh_position_xy_m", "cv_position_xy_m", "reference_position_xy_m", ...
    "packet_timestamp_s", "packet_age_s", "packet_valid", "solver", "fixed_step_s"];
evaluationFields = ["mask", "rmse_zoh_m", "rmse_cv_m", "nrmse_zoh", "nrmse_cv", ...
    "max_error_zoh_m", "max_error_cv_m", "performance_ratio", "improvement_percent", ...
    "mean_packet_age_s", "omega_delay", "omega_mean_packet_age", ...
    "omega_time_constant", "omega_sample_period"];
if ~all(isfield(simulation, simulationFields)) || ~all(isfield(evaluation, evaluationFields))
    error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d time-series schema is incomplete.", index);
end
t = double(simulation.time_s);
if ~iscolumn(t) || numel(t) < 2 || any(~isfinite(t)) || any(diff(t) <= 0)
    error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d time vector is invalid.", index);
end
n = numel(t);
xyFields = ["zoh_command_xy_m", "cv_command_xy_m", "zoh_position_xy_m", ...
    "cv_position_xy_m", "reference_position_xy_m"];
for name = xyFields
    value = simulation.(char(name));
    if ~isequal(size(value), [n, 2]) || ~isreal(value) || any(~isfinite(value), "all")
        error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d field %s has invalid shape/value.", index, name);
    end
end
for name = ["packet_timestamp_s", "packet_age_s", "packet_valid"]
    value = simulation.(char(name));
    if ~iscolumn(value) || numel(value) ~= n || ...
            (name ~= "packet_valid" && any(~isfinite(double(value))))
        error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d field %s has invalid shape/value.", index, name);
    end
end
mask = evaluation.mask;
if ~islogical(mask) || ~iscolumn(mask) || numel(mask) ~= n || ~any(mask)
    error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d evaluation mask is invalid.", index);
end
if ~isequal(size(caseResult.trajectory.position_m), [n, 2]) || ...
        ~isequal(size(caseResult.trajectory.velocity_mps), [n, 2]) || ...
        ~isequal(size(caseResult.trajectory.acceleration_mps2), [n, 2]) || ...
        ~isequal(size(caseResult.trajectory.time_s), [n, 1])
    error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d trajectory shape is not time-aligned.", index);
end
metricNames = ["rmse_zoh_m", "rmse_cv_m", "nrmse_zoh", "nrmse_cv", ...
    "max_error_zoh_m", "max_error_cv_m", "performance_ratio", ...
    "improvement_percent", "mean_packet_age_s", "omega_delay", ...
    "omega_mean_packet_age", "omega_time_constant", "omega_sample_period"];
for name = metricNames
    value = evaluation.(char(name));
    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ~isfinite(value)
        error("teleopDelay:AnalysisInputMetricInvalid", ...
            "Case %d metric %s must be a real finite scalar.", index, name);
    end
    aggregateValue = row.(char(name));
    tolerance = 64 * eps(max([1, abs(double(value)), abs(double(aggregateValue))]));
    if abs(double(value) - double(aggregateValue)) > tolerance
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "Case %d metric %s disagrees between aggregate and case.", index, name);
    end
end
condition = [double(config.trajectory.omega), double(config.communication.delay), ...
    double(config.communication.sample_period), double(config.plant.time_constant), ...
    double(config.simulation.fixed_step), double(config.simulation.dt), ...
    double(config.simulation.duration), double(config.trajectory.amplitude), ...
    double(config.evaluation.total_cycles), double(config.evaluation.warmup_cycles)];
expected = [double(row.omega_rad_s), double(row.delay_s), double(row.sample_period_s), ...
    double(row.time_constant_s), double(row.fixed_step_s), double(row.fixed_step_s), ...
    double(row.duration_s), 1.0, 10.0, double(row.warmup_cycles)];
if any(abs(condition - expected) > 64 * eps(max(1, abs(expected))))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d config conditions disagree with aggregate.", index);
end
if string(config.trajectory.type) ~= string(row.trajectory) || ...
        string(caseResult.trajectory.type) ~= string(row.trajectory) || ...
        string(simulation.solver) ~= "ode4" || ...
        abs(double(simulation.fixed_step_s) - double(row.fixed_step_s)) > 64 * eps(max(1, abs(double(row.fixed_step_s))))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d trajectory or solver contract disagrees with aggregate.", index);
end
end
