function input = load_input(inputMat)
% load_input  Load and fail-closed validate an explicit Issue #8 MAT file.

inputMat = string(inputMat);
if strlength(inputMat) == 0 || ~isfile(inputMat)
    error("teleopDelay:AnalysisInputMissing", ...
        "The explicit InputMat does not exist: %s", inputMat);
end
inputMat = string(char(java.io.File(char(inputMat)).getCanonicalPath()));
sourceSha256 = teleopdelay.experiment.sha256_file(inputMat);
try
    loaded = load(inputMat, "manifest", "aggregate", "metadata", "cases", ...
        "run_status", "experiment_id", "run_id");
catch exception
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Could not load the required Issue #8 MAT fields [%s]: %s", ...
        exception.identifier, exception.message);
end
required = ["manifest", "aggregate", "metadata", "cases", "run_status", ...
    "experiment_id", "run_id"];
if ~all(isfield(loaded, required))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input MAT is missing one or more required top-level fields.");
end
validate_input_fields(loaded);
input = loaded;
input.source_mat = inputMat;
input.source_mat_sha256 = string(sourceSha256);
input.source_experiment_id = string(loaded.experiment_id);
input.source_run_id = string(loaded.run_id);
end

function validate_input_fields(data)
metadataFields = ["experiment_id", "run_id", "run_status", "success_case_count", ...
    "failed_case_count", "total_case_count"];
manifestFields = ["schema_version", "experiment_id", "case_count", ...
    "condition_fields", "cases"];
if ~isscalar(data.metadata) || ~all(isfield(data.metadata, metadataFields)) || ...
        ~isscalar(data.manifest) || ~all(isfield(data.manifest, manifestFields))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input metadata or manifest is incomplete.");
end
if ~is_text_scalar(data.experiment_id) || ~is_text_scalar(data.run_id) || ...
        ~is_text_scalar(data.run_status) || ~is_text_scalar(data.metadata.experiment_id) || ...
        ~is_text_scalar(data.metadata.run_id) || ~is_text_scalar(data.metadata.run_status) || ...
        ~is_text_scalar(data.manifest.experiment_id)
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input identity and status fields must be scalar text values.");
end
if string(data.run_status) ~= "complete" || string(data.metadata.run_status) ~= "complete"
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input MAT must have run_status=complete.");
end
if string(data.experiment_id) ~= string(data.metadata.experiment_id) || ...
        string(data.run_id) ~= string(data.metadata.run_id) || ...
        string(data.manifest.experiment_id) ~= string(data.experiment_id)
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Top-level, metadata, and manifest identities do not agree.");
end
if data.metadata.success_case_count ~= 40 || data.metadata.failed_case_count ~= 0 || ...
        data.metadata.total_case_count ~= 40
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input metadata does not report exactly 40 successful cases.");
end
if ~isscalar(data.manifest.case_count) || data.manifest.case_count ~= 40 || ...
        ~isstruct(data.manifest.cases) || numel(data.manifest.cases) ~= 40
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input manifest must describe exactly 40 cases.");
end
if ~istable(data.aggregate) || height(data.aggregate) ~= 40
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input aggregate must contain exactly 40 rows.");
end
if ~iscell(data.cases) || numel(data.cases) ~= 40
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input cases must be a 40-element cell array.");
end

requiredAggregate = ["case_id", "trajectory", "omega_rad_s", "delay_s", ...
    "sample_period_s", "time_constant_s", "fixed_step_s", "duration_s", ...
    "warmup_cycles", "evaluation_start_s", "evaluation_end_s", "omega_delay", ...
    "mean_packet_age_s", "omega_mean_packet_age", "omega_time_constant", ...
    "omega_sample_period", "rmse_zoh_m", "rmse_cv_m", "nrmse_zoh", ...
    "nrmse_cv", "max_error_zoh_m", "max_error_cv_m", "performance_ratio", ...
    "improvement_percent", "status"];
if ~all(ismember(requiredAggregate, string(data.aggregate.Properties.VariableNames)))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input aggregate is missing required columns.");
end
if ~isstring(data.aggregate.case_id) || ~isstring(data.aggregate.trajectory) || ...
        ~isstring(data.aggregate.status)
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "aggregate case_id, trajectory, and status must be string columns.");
end
numericNames = required_numeric_columns();
for name = numericNames
    value = data.aggregate.(name{1});
    if ~isa(value, "double") || ~isreal(value) || any(~isfinite(value))
        error("teleopDelay:AnalysisInputMetricInvalid", ...
            "aggregate.%s must be a finite real double column.", name{1});
    end
end
aggregateIds = string(data.aggregate.case_id);
if numel(unique(aggregateIds)) ~= 40 || any(strlength(aggregateIds) == 0)
    error("teleopDelay:AnalysisInputDuplicateCase", ...
        "Input aggregate contains duplicate or empty case_id values.");
end
if any(data.aggregate.status ~= "success")
    error("teleopDelay:AnalysisInputIncomplete", ...
        "All aggregate rows must have status=success.");
end
requiredTrajectories = ["circle", "lissajous_1_2"];
if any(arrayfun(@(name) sum(data.aggregate.trajectory == name) ~= 20, requiredTrajectories))
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Each trajectory must have exactly 20 rows.");
end
delays = sort(unique(data.aggregate.delay_s)).';
omegas = sort(unique(data.aggregate.omega_rad_s)).';
if ~isequal(delays, [0, 0.10, 0.20, 0.40, 0.50]) || ...
        ~isequal(omegas, [0.5, 1.0, 2.0, 4.0])
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Input delay or omega grid does not match the Issue #8 standard grid.");
end
if any(arrayfun(@(delay) sum(data.aggregate.delay_s == delay) ~= 8, delays)) || ...
        any(arrayfun(@(omega) sum(data.aggregate.omega_rad_s == omega) ~= 10, omegas))
    error("teleopDelay:AnalysisInputIncomplete", ...
        "Input delay/omega marginal counts do not match the 40-case design.");
end
conditionKeys = strings(40, 1);
for index = 1:40
    conditionKeys(index) = aggregate_condition_key(data.aggregate(index, :));
end
if numel(unique(conditionKeys)) ~= 40
    error("teleopDelay:AnalysisInputDuplicateCase", ...
        "Input aggregate contains duplicate experimental conditions.");
end

manifestIds = string({data.manifest.cases.case_id}).';
if numel(unique(manifestIds)) ~= 40 || any(strlength(manifestIds) == 0) || ...
        ~isequal(sort(manifestIds), sort(aggregateIds))
    error("teleopDelay:AnalysisInputDuplicateCase", ...
        "Manifest case_id set must be unique and match aggregate.");
end
manifestKeys = strings(40, 1);
for index = 1:40
    entry = data.manifest.cases(index);
    validate_manifest_entry(entry, index);
    manifestKeys(index) = string(entry.canonical_key);
end
if numel(unique(manifestKeys)) ~= 40
    error("teleopDelay:AnalysisInputDuplicateCase", ...
        "Manifest canonical condition keys must be unique.");
end

caseIds = strings(40, 1);
for index = 1:40
    caseResult = data.cases{index};
    if ~isstruct(caseResult) || ~isscalar(caseResult) || ...
            ~all(isfield(caseResult, ["case_id", "status", "config", "trajectory", ...
            "simulation", "evaluation"]))
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "Case %d is missing the required result schema.", index);
    end
    caseIds(index) = string(caseResult.case_id);
    if string(caseResult.status) ~= "success"
        error("teleopDelay:AnalysisInputIncomplete", ...
            "All MAT cases must have status=success.");
    end
    if ~ismember(caseIds(index), aggregateIds)
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "MAT case_id does not occur in aggregate: %s", caseIds(index));
    end
    aggregateIndex = find(aggregateIds == caseIds(index), 1);
    manifestIndex = find(manifestIds == caseIds(index), 1);
    validate_case(caseResult, data.aggregate(aggregateIndex, :), ...
        data.manifest.cases(manifestIndex), index);
end
if numel(unique(caseIds)) ~= 40 || ~isequal(sort(caseIds), sort(aggregateIds))
    error("teleopDelay:AnalysisInputDuplicateCase", ...
        "MAT cases must have unique case_id values matching aggregate.");
end
end

function names = required_numeric_columns()
names = {"omega_rad_s", "delay_s", "sample_period_s", "time_constant_s", ...
    "fixed_step_s", "duration_s", "warmup_cycles", "evaluation_start_s", ...
    "evaluation_end_s", "omega_delay", "mean_packet_age_s", ...
    "omega_mean_packet_age", "omega_time_constant", "omega_sample_period", ...
    "rmse_zoh_m", "rmse_cv_m", "nrmse_zoh", "nrmse_cv", ...
    "max_error_zoh_m", "max_error_cv_m", "performance_ratio", ...
    "improvement_percent"};
end

function key = aggregate_condition_key(row)
key = strjoin([string(row.trajectory), ...
    compose("%.17g", double(row.omega_rad_s)), compose("%.17g", double(row.delay_s)), ...
    compose("%.17g", double(row.sample_period_s)), compose("%.17g", double(row.time_constant_s)), ...
    compose("%.17g", double(row.fixed_step_s)), compose("%.17g", double(row.duration_s)), ...
    compose("%.17g", double(row.warmup_cycles))], "|");
end

function validate_manifest_entry(entry, index)
required = ["case_id", "canonical_key", "trajectory", "amplitude_m", "omega_rad_s", ...
    "delay_s", "sample_period_s", "time_constant_s", "dt_s", "fixed_step_s", ...
    "total_cycles", "warmup_cycles", "solver", "nominal_duration_s", ...
    "expected_duration_s", "duration_s"];
if ~isscalar(entry) || ~all(isfield(entry, required)) || ...
        ~is_text_scalar(entry.case_id) || ~is_text_scalar(entry.canonical_key) || ...
        ~is_text_scalar(entry.trajectory) || ~is_text_scalar(entry.solver)
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Manifest case %d is incomplete.", index);
end
numericNames = setdiff(required, ["case_id", "canonical_key", "trajectory", "solver"]);
for name = numericNames
    value = entry.(char(name));
    if ~isa(value, "double") || ~isscalar(value) || ~isreal(value) || ~isfinite(value)
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "Manifest case %d field %s is not a finite scalar double.", index, name);
    end
end
end

function validate_case(caseResult, row, manifestEntry, index)
config = caseResult.config;
if ~isstruct(config) || ~isscalar(config) || ...
        ~all(isfield(config, ["trajectory", "communication", "plant", "simulation", "evaluation"])) || ...
        ~all(isfield(config.trajectory, ["type", "amplitude", "omega"])) || ...
        ~all(isfield(config.communication, ["delay", "sample_period"])) || ...
        ~all(isfield(config.plant, "time_constant")) || ...
        ~all(isfield(config.simulation, ["dt", "fixed_step", "duration", "solver"])) || ...
        ~all(isfield(config.evaluation, ["total_cycles", "warmup_cycles"]))
    error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d config is incomplete.", index);
end
if ~isstruct(caseResult.trajectory) || ~all(isfield(caseResult.trajectory, ...
        ["type", "time_s", "position_m", "velocity_mps", "acceleration_mps2"]))
    error("teleopDelay:AnalysisInputSchemaMismatch", "Case %d trajectory is incomplete.", index);
end
simulation = caseResult.simulation;
evaluation = caseResult.evaluation;
simulationFields = ["time_s", "zoh_command_xy_m", "cv_command_xy_m", ...
    "zoh_position_xy_m", "cv_position_xy_m", "reference_position_xy_m", ...
    "packet_timestamp_s", "packet_age_s", "packet_valid", "solver", "fixed_step_s"];
evaluationFields = ["period_s", "total_cycles", "warmup_cycles", "sample_start_s", ...
    "sample_end_s", "sample_count", "mask", "rmse_zoh_m", "rmse_cv_m", ...
    "nrmse_zoh", "nrmse_cv", "max_error_zoh_m", "max_error_cv_m", ...
    "performance_ratio", "improvement_percent", "mean_packet_age_s", ...
    "omega_delay", "omega_mean_packet_age", "omega_time_constant", ...
    "omega_sample_period", "zero_tolerance_m"];
if ~isstruct(simulation) || ~isstruct(evaluation) || ...
        ~all(isfield(simulation, simulationFields)) || ~all(isfield(evaluation, evaluationFields))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d time-series or evaluation schema is incomplete.", index);
end
t = simulation.time_s;
trajectoryTime = caseResult.trajectory.time_s;
if ~isa(t, "double") || ~iscolumn(t) || numel(t) < 2 || any(~isfinite(t)) || any(diff(t) <= 0) || ...
        ~isa(trajectoryTime, "double") || ~iscolumn(trajectoryTime) || ...
        ~isequal(size(trajectoryTime), size(t)) || ...
        any(abs(trajectoryTime - t) > time_tolerance(trajectoryTime, t))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d trajectory and simulation time vectors are not aligned.", index);
end
n = numel(t);
xyFields = ["position_m", "velocity_mps", "acceleration_mps2"];
for name = xyFields
    value = caseResult.trajectory.(char(name));
    if ~isa(value, "double") || ~isreal(value) || ~isequal(size(value), [n, 2]) || ...
            any(~isfinite(value), "all")
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "Case %d trajectory field %s has invalid shape or type.", index, name);
    end
end
for name = ["zoh_command_xy_m", "cv_command_xy_m", "zoh_position_xy_m", ...
        "cv_position_xy_m", "reference_position_xy_m"]
    value = simulation.(char(name));
    if ~isa(value, "double") || ~isreal(value) || ~isequal(size(value), [n, 2]) || ...
            any(~isfinite(value), "all")
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "Case %d simulation field %s has invalid shape or type.", index, name);
    end
end
for name = ["packet_timestamp_s", "packet_age_s"]
    value = simulation.(char(name));
    if ~isa(value, "double") || ~isreal(value) || ~iscolumn(value) || numel(value) ~= n || ...
            any(~isfinite(value)) || any(value < 0 & name == "packet_age_s")
        error("teleopDelay:AnalysisInputSchemaMismatch", ...
            "Case %d simulation field %s has invalid shape or type.", index, name);
    end
end
if ~islogical(simulation.packet_valid) || ~iscolumn(simulation.packet_valid) || ...
        numel(simulation.packet_valid) ~= n
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d packet_valid must be a logical column.", index);
end
mask = evaluation.mask;
if ~islogical(mask) || ~iscolumn(mask) || numel(mask) ~= n || ~any(mask)
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d evaluation mask is invalid.", index);
end
expectedMask = t >= double(row.evaluation_start_s) - time_tolerance(t, row.evaluation_start_s) & ...
    t <= double(row.evaluation_end_s) + time_tolerance(t, row.evaluation_end_s);
if ~isequal(mask, expectedMask) || ~all(simulation.packet_valid(mask))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d evaluation mask and packet_valid contract are invalid.", index);
end
if ~close_enough(t(end), row.duration_s) || ~close_enough(t(end), config.simulation.duration) || ...
        ~close_enough(t(end), manifestEntry.duration_s) || ...
        ~close_enough(evaluation.sample_start_s, row.evaluation_start_s) || ...
        ~close_enough(evaluation.sample_end_s, row.evaluation_end_s) || ...
        evaluation.sample_count ~= nnz(mask)
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d duration or evaluation sample endpoints are inconsistent.", index);
end
if ~close_enough(evaluation.period_s, 2 * pi / double(config.trajectory.omega)) || ...
        string(simulation.solver) ~= "ode4" || string(config.simulation.solver) ~= "ode4" || ...
        ~close_enough(simulation.fixed_step_s, row.fixed_step_s)
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d solver, period, or fixed-step contract is invalid.", index);
end
if ~close_enough(config.trajectory.omega, manifestEntry.omega_rad_s) || ...
        ~close_enough(config.communication.delay, manifestEntry.delay_s) || ...
        ~close_enough(config.communication.sample_period, manifestEntry.sample_period_s) || ...
        ~close_enough(config.plant.time_constant, manifestEntry.time_constant_s) || ...
        ~close_enough(config.simulation.dt, manifestEntry.dt_s) || ...
        ~close_enough(config.simulation.fixed_step, manifestEntry.fixed_step_s) || ...
        ~close_enough(config.simulation.duration, manifestEntry.duration_s) || ...
        ~close_enough(config.trajectory.amplitude, manifestEntry.amplitude_m) || ...
        double(config.evaluation.total_cycles) ~= manifestEntry.total_cycles || ...
        double(config.evaluation.warmup_cycles) ~= manifestEntry.warmup_cycles || ...
        string(config.trajectory.type) ~= string(manifestEntry.trajectory) || ...
        string(caseResult.trajectory.type) ~= string(manifestEntry.trajectory) || ...
        string(simulation.solver) ~= string(manifestEntry.solver)
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d config does not match its manifest condition.", index);
end
if string(manifestEntry.case_id) ~= string(row.case_id) || ...
        string(manifestEntry.trajectory) ~= string(row.trajectory) || ...
        ~close_enough(manifestEntry.omega_rad_s, row.omega_rad_s) || ...
        ~close_enough(manifestEntry.delay_s, row.delay_s) || ...
        ~close_enough(manifestEntry.sample_period_s, row.sample_period_s) || ...
        ~close_enough(manifestEntry.time_constant_s, row.time_constant_s) || ...
        ~close_enough(manifestEntry.fixed_step_s, row.fixed_step_s) || ...
        ~close_enough(manifestEntry.duration_s, row.duration_s) || ...
        double(manifestEntry.warmup_cycles) ~= row.warmup_cycles
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d manifest and aggregate condition do not match.", index);
end

metricNames = ["rmse_zoh_m", "rmse_cv_m", "nrmse_zoh", "nrmse_cv", ...
    "max_error_zoh_m", "max_error_cv_m", "performance_ratio", ...
    "improvement_percent", "mean_packet_age_s", "omega_delay", ...
    "omega_mean_packet_age", "omega_time_constant", "omega_sample_period"];
for name = metricNames
    value = evaluation.(char(name));
    if ~isa(value, "double") || ~isscalar(value) || ~isreal(value) || ~isfinite(value)
        error("teleopDelay:AnalysisInputMetricInvalid", ...
            "Case %d metric %s must be a real finite double scalar.", index, name);
    end
end
zohError = simulation.zoh_position_xy_m(mask, :) - simulation.reference_position_xy_m(mask, :);
cvError = simulation.cv_position_xy_m(mask, :) - simulation.reference_position_xy_m(mask, :);
rmseZoh = sqrt(mean(sum(zohError.^2, 2)));
rmseCv = sqrt(mean(sum(cvError.^2, 2)));
maxZoh = max(vecnorm(zohError, 2, 2));
maxCv = max(vecnorm(cvError, 2, 2));
amplitude = double(config.trajectory.amplitude);
zeroTolerance = 32 * eps(max([1, abs(rmseZoh), abs(rmseCv)]));
if rmseZoh <= zeroTolerance && rmseCv <= zeroTolerance
    expectedRatio = 1.0;
    expectedImprovement = 0.0;
elseif rmseZoh <= zeroTolerance
    error("teleopDelay:AnalysisInputMetricInvalid", ...
        "Case %d violates the zero-denominator performance-ratio contract.", index);
else
    expectedRatio = rmseCv / rmseZoh;
    expectedImprovement = (1 - expectedRatio) * 100;
end
expected = [rmseZoh, rmseCv, rmseZoh / amplitude, rmseCv / amplitude, ...
    maxZoh, maxCv, expectedRatio, expectedImprovement, mean(simulation.packet_age_s(mask)), ...
    config.trajectory.omega * config.communication.delay, ...
    config.trajectory.omega * mean(simulation.packet_age_s(mask)), ...
    config.trajectory.omega * config.plant.time_constant, ...
    config.trajectory.omega * config.communication.sample_period, zeroTolerance];
actual = [evaluation.rmse_zoh_m, evaluation.rmse_cv_m, evaluation.nrmse_zoh, ...
    evaluation.nrmse_cv, evaluation.max_error_zoh_m, evaluation.max_error_cv_m, ...
    evaluation.performance_ratio, evaluation.improvement_percent, evaluation.mean_packet_age_s, ...
    evaluation.omega_delay, evaluation.omega_mean_packet_age, evaluation.omega_time_constant, ...
    evaluation.omega_sample_period, evaluation.zero_tolerance_m];
if any(abs(actual - expected) > metric_tolerance(actual, expected))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d evaluation metrics disagree with the saved time series or config.", index);
end
aggregateActual = double(row{1, metricNames});
if any(abs(aggregateActual - actual(1:numel(metricNames))) > ...
        metric_tolerance(aggregateActual, actual(1:numel(metricNames))))
    error("teleopDelay:AnalysisInputSchemaMismatch", ...
        "Case %d aggregate metrics disagree with case evaluation.", index);
end
end

function result = is_text_scalar(value)
result = (isstring(value) || ischar(value)) && isscalar(string(value)) && strlength(string(value)) > 0;
end

function tolerance = time_tolerance(first, second)
first = double(first(:));
second = double(second(:));
count = max(numel(first), numel(second));
if isscalar(first)
    first = repmat(first, count, 1);
end
if isscalar(second)
    second = repmat(second, count, 1);
end
tolerance = 64 * eps(max([ones(count, 1), abs(first), abs(second)], [], 2));
end

function result = close_enough(first, second)
result = isscalar(first) && isscalar(second) && isreal(first) && isreal(second) && ...
    isfinite(first) && isfinite(second) && abs(double(first) - double(second)) <= ...
    128 * eps(max([1, abs(double(first)), abs(double(second))]));
end

function tolerance = metric_tolerance(first, second)
tolerance = 128 * eps(max([ones(numel(first), 1), abs(double(first(:))), ...
    abs(double(second(:)))], [], 2)).';
end
