function artifact = persist(analysis, outputRoot, projectRoot)
% persist  Atomically persist Issue #9 tables, figures, and metadata.

experimentId = char(string(analysis.input.source_experiment_id));
analysisId = char(string(analysis.analysis_id));
targetParent = fullfile(char(outputRoot), "analysis", experimentId, analysisId);
if ~isfolder(targetParent)
    mkdir(targetParent);
end
git = teleopdelay.experiment.git_context(projectRoot);
runId = allocate_run_id(targetParent, git.short_sha);
targetDirectory = fullfile(targetParent, runId);
temporaryDirectory = tempname(targetParent);
mkdir(temporaryDirectory);
cleanup = onCleanup(@() remove_temporary(temporaryDirectory));
figuresDirectory = fullfile(temporaryDirectory, "figures");
mkdir(figuresDirectory);

figureManifest = teleopdelay.analysis.render_all(analysis.input, analysis, figuresDirectory, analysis.config);
figure_manifest = figureManifest;
tableMap = table_map(analysis.tables);
for index = 1:size(tableMap, 1)
    writetable(tableMap.table{index}, fullfile(temporaryDirectory, tableMap.filename(index)), ...
        "WriteVariableNames", true);
end
writetable(figureManifest, fullfile(temporaryDirectory, "figure_manifest.csv"), ...
    "WriteVariableNames", true);

metadata = build_metadata(analysis, projectRoot, git, runId, temporaryDirectory, figureManifest);
convergence = analysis.tables.convergence;
convergence_artifact = analysis.convergence;
convergence_metadata = analysis.convergence.metadata;
convergence_diagnostics = analysis.convergence.diagnostics;
case_classification = analysis.tables.case_classification;
extreme_cases = analysis.tables.extreme_cases;
nearest_boundary_cases = analysis.tables.nearest_boundary_cases;
boundary_brackets = analysis.tables.boundary_brackets;
representative_cases = analysis.tables.representative_cases;
instantaneous_error_extremes = analysis.tables.instantaneous_error_extremes;
dimensionless_diagnostics = analysis.tables.dimensionless_diagnostics;
identifiability = analysis.tables.identifiability;
theory = analysis.theory;
tolerance_contract = analysis.tolerance_contract;
analysis_id = analysis.analysis_id;
analysis_schema_version = analysis.analysis_schema_version;
convergence_schema_version = analysis.config.convergence.schema_version;
save(fullfile(temporaryDirectory, "analysis_tables.mat"), ...
    "case_classification", "extreme_cases", "nearest_boundary_cases", ...
    "boundary_brackets", "representative_cases", "instantaneous_error_extremes", ...
    "dimensionless_diagnostics", "identifiability", ...
    "figureManifest", "metadata", "convergence", "convergence_artifact", ...
    "convergence_metadata", "theory", "tolerance_contract", ...
    "figure_manifest", ...
    "analysis_id", "analysis_schema_version", "convergence_schema_version", ...
    "convergence_diagnostics", "-v7.3");

files = build_file_manifest(temporaryDirectory, ["analysis_tables.mat", "artifact_manifest.csv"]);
metadata.output_directory_relative = "results/generated/analysis/" + ...
    string(experimentId) + "/" + string(analysisId) + "/" + string(runId);
metadata.output_files = files;
metadata.output_filenames = string(files.relative_path);
metadata.output_sha256_note = "analysis_tables.mat contains this metadata; its self-hash is intentionally not embedded.";
save(fullfile(temporaryDirectory, "analysis_tables.mat"), ...
    "case_classification", "extreme_cases", "nearest_boundary_cases", ...
    "boundary_brackets", "representative_cases", "instantaneous_error_extremes", ...
    "dimensionless_diagnostics", "identifiability", ...
    "figureManifest", "metadata", "convergence", "convergence_artifact", ...
    "convergence_metadata", "theory", "tolerance_contract", ...
    "figure_manifest", ...
    "analysis_id", "analysis_schema_version", "convergence_schema_version", ...
    "convergence_diagnostics", "-v7.3");
files = build_file_manifest(temporaryDirectory, "artifact_manifest.csv");
writetable(files, fullfile(temporaryDirectory, "artifact_manifest.csv"), ...
    "WriteVariableNames", true);
files = build_file_manifest(temporaryDirectory, "artifact_manifest.csv");
if isfolder(targetDirectory) || isfile(targetDirectory)
    error("teleopDelay:AnalysisResultExists", "Analysis run directory already exists: %s", targetDirectory);
end
[moved, message] = movefile(temporaryDirectory, targetDirectory);
if ~moved
    error("teleopDelay:AnalysisAtomicSaveFailed", "Could not atomically move analysis artifact: %s", message);
end
clear cleanup;
artifact = struct("saved", true, "analysis_id", string(analysisId), ...
    "run_directory", string(targetDirectory), "figure_manifest", figureManifest, ...
    "files", files);
end

function runId = allocate_run_id(parent, shortSha)
nowValue = datetime("now", "TimeZone", "UTC");
nowValue.Format = "yyyyMMdd'T'HHmmssSSS'Z'";
runId = string(nowValue) + "__" + string(shortSha);
suffix = 0;
while isfolder(fullfile(parent, runId))
    suffix = suffix + 1;
    runId = string(nowValue) + "__" + string(shortSha) + "__r" + string(suffix);
end
end

function mapping = table_map(tables)
mapping = table( ...
    {tables.case_classification; tables.extreme_cases; tables.nearest_boundary_cases; ...
    tables.boundary_brackets; tables.representative_cases; tables.instantaneous_error_extremes; ...
    tables.dimensionless_diagnostics; tables.identifiability; tables.convergence}, ...
    ["case_classification.csv"; "extreme_cases.csv"; "nearest_boundary_cases.csv"; ...
    "boundary_brackets.csv"; "representative_cases.csv"; "instantaneous_error_extremes.csv"; ...
    "dimensionless_diagnostics.csv"; "identifiability.csv"; "convergence.csv"], ...
    'VariableNames', {'table', 'filename'});
end

function metadata = build_metadata(analysis, projectRoot, git, runId, temporaryDirectory, figureManifest)
sourceMetadata = analysis.input.metadata;
modelHashBefore = "unknown";
modelHashAfter = "unknown";
if isstruct(analysis.convergence) && isfield(analysis.convergence, "metadata") && ...
        isfield(analysis.convergence.metadata, "model_hash_before")
    modelHashBefore = string(analysis.convergence.metadata.model_hash_before);
    modelHashAfter = string(analysis.convergence.metadata.model_hash_after);
end
simulinkVersion = "unknown";
try
    products = ver("simulink");
    if ~isempty(products)
        simulinkVersion = string(products(1).Version);
    end
catch
end
metadata = struct( ...
    "source_mat_absolute_path", string(analysis.input.source_mat), ...
    "source_mat_sha256", string(analysis.input.source_mat_sha256), ...
    "source_experiment_id", string(analysis.input.source_experiment_id), ...
    "source_run_id", string(analysis.input.source_run_id), ...
    "source_git_sha", string(sourceMetadata.git_commit_sha), ...
    "analysis_git_sha", string(git.commit_sha), ...
    "analysis_git_dirty_state", string(git.dirty_state), ...
    "analysis_schema_version", string(analysis.analysis_schema_version), ...
    "analysis_id", string(analysis.analysis_id), ...
    "analysis_run_id", string(runId), ...
    "mode", string(analysis.mode), ...
    "matlab_version", string(version), ...
    "simulink_version", simulinkVersion, ...
    "started_at_utc", string(analysis.started_at_utc), ...
    "finished_at_utc", string(analysis.finished_at_utc), ...
    "boundary_tolerance", analysis.tolerance_contract.boundary_tolerance, ...
    "boundary_tolerance_contract", analysis.tolerance_contract, ...
    "theoretical_candidate_definition", string(analysis.theory.definition), ...
    "theoretical_candidate_source", string(analysis.theory.source), ...
    "theoretical_q_candidate", analysis.theory.q_candidate, ...
    "selected_case_ids", string(analysis.tables.representative_cases.case_id), ...
    "classification_counts", analysis.tables.classification_counts, ...
    "trajectory_counts", analysis.tables.trajectory_counts, ...
    "convergence_available", logical(analysis.convergence.available), ...
    "convergence_source", string(analysis.convergence_source), ...
    "convergence_metadata", analysis.convergence.metadata, ...
    "convergence_diagnostics", analysis.convergence.diagnostics, ...
    "convergence_schema_version", string(analysis.config.convergence.schema_version), ...
    "event_acceleration_percentile", double(analysis.config.event_acceleration_percentile), ...
    "model_hash_before", modelHashBefore, ...
    "model_hash_after", modelHashAfter, ...
    "figure_count", height(figureManifest), ...
    "project_root", string(projectRoot), ...
    "temporary_directory_used", string(temporaryDirectory));
end

function files = build_file_manifest(directory, excludedNames)
if nargin < 2
    excludedNames = strings(0, 1);
end
excludedNames = string(excludedNames);
paths = dir(fullfile(directory, "**", "*"));
paths = paths(~[paths.isdir]);
paths = paths(~ismember(string({paths.name}), excludedNames));
rows = cell(numel(paths), 3);
for index = 1:numel(paths)
    fullPath = fullfile(paths(index).folder, paths(index).name);
    relative = erase(string(fullPath), string(directory) + filesep);
    rows(index, :) = {relative, double(paths(index).bytes), ...
        teleopdelay.experiment.sha256_file(fullPath)};
end
files = cell2table(rows, 'VariableNames', {'relative_path', 'size_bytes', 'sha256'});
files = sortrows(files, "relative_path");
end

function remove_temporary(directory)
if isfolder(directory)
    rmdir(directory, "s");
end
end
