function entry = render_system_architecture(figuresDirectory, config)
% render_system_architecture  Draw the fixed model-contract system diagram.

contract = teleopdelay.analysis.architecture_contract();
textContract = teleopdelay.analysis.figure_text_contract();
fig = figure("Visible", "off", "Color", "white", "Position", [100, 100, 1500, 850]);
cleanup = onCleanup(@() teleopdelay.analysis.close_figure(fig));
axes(fig, "Visible", "off", "Position", [0, 0, 1, 1]);
geometry = teleopdelay.analysis.architecture_geometry();
if ~isempty(geometry.crossings)
    error("teleopDelay:AnalysisArchitectureGeometryCrossing", ...
        "Architecture edge crosses an intermediate node box.");
end
positions = geometry.positions;
colors = node_colors();
annotation(fig, "textbox", [0.03, 0.92, 0.94, 0.05], ...
    "String", textContract.figure_01.title, "EdgeColor", "none", ...
    "HorizontalAlignment", "center", "FontSize", 18, "Interpreter", "none");
for index = 1:numel(contract.nodes)
    node = char(contract.nodes(index));
    annotation(fig, "textbox", positions.(node), ...
        "String", contract.labels(index), "FitBoxToText", "off", ...
        "HorizontalAlignment", "center", "VerticalAlignment", "middle", ...
        "FontSize", 11, "BackgroundColor", colors.(node), ...
        "Color", [0.05, 0.05, 0.05], "Interpreter", "none");
end
for index = 1:numel(geometry.edges)
    draw_edge(fig, geometry.edges(index).points);
end
annotation(fig, "textbox", [0.30, 0.06, 0.40, 0.05], ...
    "String", contract.plant_model + "。" + contract.evaluation_note + "。", ...
    "EdgeColor", "none", "HorizontalAlignment", "center", ...
    "FontSize", 11, "Interpreter", "none");
fontName = teleopdelay.analysis.style_figure(fig);
metadata = struct( ...
    "trajectory", "all", "case_ids", "", "caption", textContract.figure_01.caption, ...
    "metric", textContract.figure_01.metric, "axes_contract", textContract.figure_01.axes_contract, ...
    "font_name", fontName);
entry = teleopdelay.analysis.save_figure(fig, figuresDirectory, ...
    "figure_01_system_architecture", metadata, config.figure_dpi);
teleopdelay.analysis.close_figure(fig);
clear cleanup;
end

function colors = node_colors()
colors = struct( ...
    "continuous_target", [0.86, 0.92, 1.00], ...
    "sender_sampling", [0.90, 0.96, 0.90], ...
    "fixed_delay", [1.00, 0.94, 0.82], ...
    "latest_packet", [0.95, 0.95, 0.95], ...
    "zoh_reconstruction", [1.00, 0.90, 0.90], ...
    "cv_reconstruction", [0.90, 0.94, 1.00], ...
    "reference_plant", [0.92, 0.88, 1.00], ...
    "zoh_plant", [1.00, 0.90, 0.90], ...
    "cv_plant", [0.90, 0.94, 1.00], ...
    "evaluation", [0.95, 0.95, 0.95]);
end

function draw_edge(fig, points)
for segment = 1:size(points, 1) - 2
    annotation(fig, "line", [points(segment, 1), points(segment + 1, 1)], ...
        [points(segment, 2), points(segment + 1, 2)], "LineWidth", 1.5, ...
        "Color", [0.15, 0.15, 0.15]);
end
annotation(fig, "arrow", [points(end - 1, 1), points(end, 1)], ...
    [points(end - 1, 2), points(end, 2)], "LineWidth", 1.5, ...
    "Color", [0.15, 0.15, 0.15]);
end
