function entry = render_system_architecture(figuresDirectory, config)
% render_system_architecture  Draw the fixed model-contract system diagram.

contract = teleopdelay.analysis.architecture_contract();
textContract = teleopdelay.analysis.figure_text_contract();
fig = figure("Visible", "off", "Color", "white", "Position", [100, 100, 1500, 850]);
cleanup = onCleanup(@() teleopdelay.analysis.close_figure(fig));
axes(fig, "Visible", "off", "Position", [0, 0, 1, 1]);
positions = node_positions();
colors = node_colors();
annotation(fig, "textbox", [0.03, 0.92, 0.94, 0.05], ...
    "String", textContract.figure_01.title, "EdgeColor", "none", ...
    "HorizontalAlignment", "center", "FontSize", 18, "Interpreter", "none");
for index = 1:numel(contract.nodes)
    node = char(contract.nodes(index));
    annotation(fig, "textbox", positions.(node), ...
        "String", contract.labels(index), "FitBoxToText", "off", ...
        "HorizontalAlignment", "center", "VerticalAlignment", "middle", ...
        "FontSize", 11, "BackgroundColor", colors.(node), ...
        "Color", [0.05, 0.05, 0.05], "Interpreter", "none");
end
for index = 1:size(contract.required_edges, 1)
    source = char(contract.required_edges(index, 1));
    target = char(contract.required_edges(index, 2));
    [sourcePoint, targetPoint] = boundary_points(positions.(source), positions.(target));
    annotation(fig, "arrow", [sourcePoint(1), targetPoint(1)], ...
        [sourcePoint(2), targetPoint(2)], "LineWidth", 1.5, ...
        "Color", [0.15, 0.15, 0.15]);
end
annotation(fig, "textbox", [0.30, 0.06, 0.40, 0.05], ...
    "String", contract.plant_model + "。" + contract.evaluation_note + "。", ...
    "EdgeColor", "none", "HorizontalAlignment", "center", ...
    "FontSize", 11, "Interpreter", "none");
fontName = teleopdelay.analysis.style_figure(fig);
metadata = struct( ...
    "trajectory", "all", "case_ids", "", "caption", textContract.figure_01.caption, ...
    "metric", textContract.figure_01.metric, "axes_contract", textContract.figure_01.axes_contract, ...
    "font_name", fontName);
entry = teleopdelay.analysis.save_figure(fig, figuresDirectory, ...
    "figure_01_system_architecture", metadata, config.figure_dpi);
teleopdelay.analysis.close_figure(fig);
clear cleanup;
end

function positions = node_positions()
positions = struct( ...
    "continuous_target", [0.03, 0.72, 0.15, 0.10], ...
    "sender_sampling", [0.21, 0.72, 0.15, 0.10], ...
    "fixed_delay", [0.39, 0.72, 0.15, 0.10], ...
    "latest_packet", [0.57, 0.70, 0.20, 0.14], ...
    "zoh_reconstruction", [0.48, 0.46, 0.16, 0.10], ...
    "cv_reconstruction", [0.48, 0.20, 0.16, 0.10], ...
    "reference_plant", [0.22, 0.20, 0.18, 0.10], ...
    "zoh_plant", [0.70, 0.46, 0.12, 0.10], ...
    "cv_plant", [0.70, 0.20, 0.12, 0.10], ...
    "evaluation", [0.87, 0.42, 0.10, 0.20]);
end

function colors = node_colors()
colors = struct( ...
    "continuous_target", [0.86, 0.92, 1.00], ...
    "sender_sampling", [0.90, 0.96, 0.90], ...
    "fixed_delay", [1.00, 0.94, 0.82], ...
    "latest_packet", [0.95, 0.95, 0.95], ...
    "zoh_reconstruction", [1.00, 0.90, 0.90], ...
    "cv_reconstruction", [0.90, 0.94, 1.00], ...
    "reference_plant", [0.92, 0.88, 1.00], ...
    "zoh_plant", [1.00, 0.90, 0.90], ...
    "cv_plant", [0.90, 0.94, 1.00], ...
    "evaluation", [0.95, 0.95, 0.95]);
end

function [sourcePoint, targetPoint] = boundary_points(source, target)
sourceCenter = [source(1) + source(3) / 2, source(2) + source(4) / 2];
targetCenter = [target(1) + target(3) / 2, target(2) + target(4) / 2];
direction = targetCenter - sourceCenter;
sourcePoint = sourceCenter + rectangle_intersection(source, direction);
targetPoint = targetCenter - rectangle_intersection(target, direction);
end

function offset = rectangle_intersection(rectangle, direction)
if all(direction == 0)
    error("teleopDelay:AnalysisArchitectureGeometryInvalid", ...
        "Architecture edge endpoints cannot share a node center.");
end
halfWidth = rectangle(3) / 2;
halfHeight = rectangle(4) / 2;
scales = [halfWidth / abs(direction(1)), halfHeight / abs(direction(2))];
scales(~isfinite(scales)) = inf;
offset = direction * min(scales);
end
