function convergence = run_convergence(input, representatives, projectRoot, config)
% run_convergence  Run only representative cases at half fixed step.

baseStep = config.convergence.base_fixed_step_s;
refinedStep = config.convergence.refined_fixed_step_s;
samplePeriod = config.convergence.sample_period_s;
alignmentRatio = samplePeriod / refinedStep;
if abs(alignmentRatio - round(alignmentRatio)) > config.convergence.alignment_tolerance
    error("teleopDelay:AnalysisConvergenceAlignment", ...
        "Refined fixed step does not align with the sample period.");
end
roleMask = representatives.role == "best_improvement" | ...
    startsWith(representatives.role, "worst_degradation") | ...
    representatives.role == "nearest_boundary";
roleTable = representatives(roleMask, {'trajectory', 'role', 'case_id'});
[uniqueIds, ~, roleIndex] = unique(roleTable.case_id, "stable");
pathBefore = path;
directoryBefore = pwd;
baseNamesBefore = string(evalin("base", "who"));
modelPaths = teleopdelay.simulink.model_paths(projectRoot);
modelFiles = [string(modelPaths.system), string(modelPaths.communication), string(modelPaths.plant)];
hashBefore = cellstr(arrayfun(@(file) teleopdelay.experiment.sha256_file(file), modelFiles));
rows = cell(0, 30);
cleanup = onCleanup(@() close_models(modelPaths));
for caseIndex = 1:numel(uniqueIds)
    caseId = uniqueIds(caseIndex);
    sourceCase = find_case(input, caseId);
    definition = input.manifest.cases(find_manifest_case(input.manifest, caseId));
    if abs(double(definition.fixed_step_s) - baseStep) > 64 * eps(max(1, baseStep)) || ...
            abs(double(definition.sample_period_s) - samplePeriod) > 64 * eps(max(1, samplePeriod))
        error("teleopDelay:AnalysisConvergenceConfigMismatch", ...
            "Case %s does not match the fixed convergence contract.", caseId);
    end
    refinedDefinition = definition;
    refinedDefinition.dt_s = refinedStep;
    refinedDefinition.fixed_step_s = refinedStep;
    refinedOutput = teleopdelay.experiment.execute_case(refinedDefinition, projectRoot);
    metrics = refinedOutput.evaluation;
    if ~all(isfinite([metrics.rmse_zoh_m, metrics.rmse_cv_m, metrics.performance_ratio, ...
            metrics.max_error_zoh_m, metrics.max_error_cv_m]))
        error("teleopDelay:AnalysisConvergenceFailed", ...
            "Refined convergence metrics are nonfinite for %s.", caseId);
    end
    alignmentValid = abs(samplePeriod / refinedOutput.config.simulation.fixed_step - ...
        round(samplePeriod / refinedOutput.config.simulation.fixed_step)) <= ...
        config.convergence.alignment_tolerance;
    roles = roleTable.role(roleIndex == caseIndex);
    roleMapping = strjoin(cellstr(roles), "|");
    baseG = double(sourceCase.evaluation.performance_ratio);
    refinedG = double(metrics.performance_ratio);
    rows(end + 1, :) = {string(roles(1)), string(roleMapping), string(sourceCase.config.trajectory.type), ...
        string(caseId), double(sourceCase.config.trajectory.omega), double(sourceCase.config.communication.delay), ...
        baseStep, refinedStep, samplePeriod, double(sourceCase.evaluation.rmse_zoh_m), ...
        double(metrics.rmse_zoh_m), double(sourceCase.evaluation.rmse_cv_m), double(metrics.rmse_cv_m), ...
        baseG, refinedG, double(metrics.rmse_zoh_m - sourceCase.evaluation.rmse_zoh_m), ...
        double(metrics.rmse_cv_m - sourceCase.evaluation.rmse_cv_m), double(refinedG - baseG), ...
        relative_delta(metrics.rmse_zoh_m, sourceCase.evaluation.rmse_zoh_m), ...
        relative_delta(metrics.rmse_cv_m, sourceCase.evaluation.rmse_cv_m), ...
        relative_delta(refinedG, baseG), double(sourceCase.evaluation.max_error_zoh_m), ...
        double(metrics.max_error_zoh_m), double(sourceCase.evaluation.max_error_cv_m), ...
        double(metrics.max_error_cv_m), double(metrics.max_error_zoh_m - sourceCase.evaluation.max_error_zoh_m), ...
        double(metrics.max_error_cv_m - sourceCase.evaluation.max_error_cv_m), ...
        double(samplePeriod / refinedStep), logical(alignmentValid), "validated"}; %#ok<AGROW>
end
close_models(modelPaths);
pathRestored = isequal(path, pathBefore);
directoryRestored = isequal(pwd, directoryBefore);
baseNamesAfter = string(evalin("base", "who"));
modelHashesAfter = cellstr(arrayfun(@(file) teleopdelay.experiment.sha256_file(file), modelFiles));
if ~pathRestored || ~directoryRestored || ~isequal(sort(baseNamesBefore), sort(baseNamesAfter)) || ...
        ~isequal(hashBefore, modelHashesAfter)
    error("teleopDelay:AnalysisConvergenceHygiene", ...
        "Convergence study did not restore path, pwd, base workspace, or model hashes.");
end
convergence = struct( ...
    "available", true, ...
    "source", "full-mode-execution", ...
    "table", teleopdelay.analysis.convergence_table(rows), ...
    "metadata", struct( ...
        "base_fixed_step_s", baseStep, ...
        "refined_fixed_step_s", refinedStep, ...
        "sample_period_s", samplePeriod, ...
        "alignment_ratio", alignmentRatio, ...
        "alignment_valid", true, ...
        "path_restored", pathRestored, ...
        "pwd_restored", directoryRestored, ...
        "base_workspace_unchanged", isequal(sort(baseNamesBefore), sort(baseNamesAfter)), ...
        "model_hash_before", string(hashBefore), ...
        "model_hash_after", string(modelHashesAfter)));
clear cleanup;
end

function value = relative_delta(refined, base)
value = abs(double(refined) - double(base)) / max(1, abs(double(base)));
end

function caseResult = find_case(input, caseId)
ids = cellfun(@(value) string(value.case_id), input.cases);
caseResult = input.cases{find(ids == string(caseId), 1)};
end

function index = find_manifest_case(manifest, caseId)
ids = string({manifest.cases.case_id});
index = find(ids == string(caseId), 1);
end

function close_models(paths)
names = [string(paths.systemModelName), string(paths.communicationModelName), string(paths.plantModelName)];
for name = names
    if bdIsLoaded(char(name))
        close_system(char(name), 0);
    end
end
end
