function entry = save_figure(fig, figuresDirectory, figureId, metadata, dpi)
% save_figure  Export one headless report figure in PNG and vector PDF form.

fontName = teleopdelay.analysis.style_figure(fig);
if ~isfield(metadata, "font_name")
    metadata.font_name = fontName;
end

pngName = string(figureId) + ".png";
pdfName = string(figureId) + ".pdf";
pngPath = fullfile(figuresDirectory, pngName);
pdfPath = fullfile(figuresDirectory, pdfName);
drawnow;
exportgraphics(fig, pngPath, "Resolution", dpi);
exportgraphics(fig, pdfPath, "ContentType", "vector");
if ~isfile(pngPath) || ~isfile(pdfPath)
    error("teleopDelay:AnalysisFigureSaveFailed", "Figure export failed for %s.", figureId);
end
pngInfo = dir(pngPath);
pdfInfo = dir(pdfPath);
entry = struct( ...
    "figure_id", string(figureId), ...
    "filename_png", pngName, ...
    "filename_pdf", pdfName, ...
    "file_size_png", double(pngInfo.bytes), ...
    "file_size_pdf", double(pdfInfo.bytes), ...
    "sha256_png", teleopdelay.experiment.sha256_file(pngPath), ...
    "sha256_pdf", teleopdelay.experiment.sha256_file(pdfPath), ...
    "trajectory", string(metadata.trajectory), ...
    "case_ids", string(metadata.case_ids), ...
    "caption", string(metadata.caption), ...
    "metric", string(metadata.metric), ...
    "axes_contract", string(metadata.axes_contract), ...
    "font_name", string(metadata.font_name), ...
    "vector_pdf", true, ...
    "dpi", double(dpi));
end
