function theory = theory()
% theory  Ideal sinusoid ZOH/CV equality candidate and diagnostic formulas.

f = @(q) q - 2 * sin(q);
qCandidate = fzero(f, [1, 3]);
if ~(qCandidate > 0 && abs(f(qCandidate)) <= 128 * eps(max(1, abs(qCandidate))))
    error("teleopDelay:AnalysisTheoryInvalid", "Could not determine the nonzero q candidate.");
end
theory = struct( ...
    "q_candidate", double(qCandidate), ...
    "equation", "q = 2 sin(q)", ...
    "definition", "First positive nonzero root of ideal sinusoid E_CV=E_ZOH.", ...
    "source", "Analytic derivation required by Issue #9; not a literature value.", ...
    "zoh_error_squared", @(q) 2 * (1 - cos(q)), ...
    "cv_error_squared", @(q) (1 - cos(q)).^2 + (q - sin(q)).^2);
end
