function metadata = execution_metadata(manifest, runId, projectRoot, ...
        startedAtUtc, finishedAtUtc, caseResults, runStatus)
% execution_metadata  Create the reproducibility metadata stored in MAT.

git = teleopdelay.experiment.git_context(projectRoot);
successCount = 0;
failedCount = 0;
for index = 1:numel(caseResults)
    if string(caseResults{index}.status) == "success"
        successCount = successCount + 1;
    else
        failedCount = failedCount + 1;
    end
end
matlabVersion = string(version);
simulinkVersion = "unknown";
try
    products = ver("simulink");
    if ~isempty(products)
        simulinkVersion = string(products(1).Version);
    end
catch
    simulinkVersion = "unknown";
end
metadata = struct( ...
    "experiment_id", string(manifest.experiment_id), ...
    "manifest_schema_version", string(manifest.schema_version), ...
    "started_at_utc", string(startedAtUtc), ...
    "finished_at_utc", string(finishedAtUtc), ...
    "matlab_version", matlabVersion, ...
    "simulink_version", simulinkVersion, ...
    "git_commit_sha", git.commit_sha, ...
    "git_dirty_state", git.dirty_state, ...
    "runner_version", "issue8.runner.v1", ...
    "total_case_count", double(numel(caseResults)), ...
    "success_case_count", double(successCount), ...
    "failed_case_count", double(failedCount), ...
    "run_status", string(runStatus), ...
    "run_id", string(runId));
end
