function validate_case_output(output, definition)
% validate_case_output  Bind one successful output to its manifest definition.

if ~isstruct(output) || ~isscalar(output) || ...
        ~all(isfield(output, ["config", "trajectory", "simulation", "evaluation"]))
    error("teleopDelay:ExperimentCaseOutputInvalid", ...
        "A successful case executor must return config, trajectory, simulation, and evaluation.");
end

config = require_struct(output, "config", "output.config");
trajectoryConfig = require_struct(config, "trajectory", "output.config.trajectory");
communicationConfig = require_struct(config, "communication", "output.config.communication");
plantConfig = require_struct(config, "plant", "output.config.plant");
simulationConfig = require_struct(config, "simulation", "output.config.simulation");
evaluationConfig = require_struct(config, "evaluation", "output.config.evaluation");

compare_string(required_field(trajectoryConfig, "type", "output.config.trajectory"), ...
    definition.trajectory, "output.config.trajectory.type");
compare_double(required_field(trajectoryConfig, "amplitude", "output.config.trajectory"), ...
    definition.amplitude_m, "output.config.trajectory.amplitude");
compare_double(required_field(trajectoryConfig, "omega", "output.config.trajectory"), ...
    definition.omega_rad_s, "output.config.trajectory.omega");
compare_double(required_field(communicationConfig, "delay", "output.config.communication"), ...
    definition.delay_s, "output.config.communication.delay");
compare_double(required_field(communicationConfig, "sample_period", ...
    "output.config.communication"), definition.sample_period_s, ...
    "output.config.communication.sample_period");
compare_double(required_field(plantConfig, "time_constant", "output.config.plant"), ...
    definition.time_constant_s, "output.config.plant.time_constant");
compare_double(required_field(simulationConfig, "dt", "output.config.simulation"), ...
    definition.dt_s, "output.config.simulation.dt");
compare_double(required_field(simulationConfig, "fixed_step", "output.config.simulation"), ...
    definition.fixed_step_s, "output.config.simulation.fixed_step");
compare_double(required_field(simulationConfig, "duration", "output.config.simulation"), ...
    definition.duration_s, "output.config.simulation.duration");
compare_string(required_field(simulationConfig, "solver", "output.config.simulation"), ...
    definition.solver, "output.config.simulation.solver");
compare_integer(required_field(evaluationConfig, "total_cycles", "output.config.evaluation"), ...
    definition.total_cycles, "output.config.evaluation.total_cycles");
compare_integer(required_field(evaluationConfig, "warmup_cycles", "output.config.evaluation"), ...
    definition.warmup_cycles, "output.config.evaluation.warmup_cycles");

trajectory = require_struct(output, "trajectory", "output.trajectory");
compare_string(required_field(trajectory, "type", "output.trajectory"), ...
    definition.trajectory, "output.trajectory.type");

simulation = require_struct(output, "simulation", "output.simulation");
time_s = required_field(simulation, "time_s", "output.simulation");
if ~(isa(time_s, "double") && iscolumn(time_s) && ~isempty(time_s) && ...
        isreal(time_s) && all(isfinite(time_s)))
    error("teleopDelay:ExperimentCaseOutputInvalid", ...
        "output.simulation.time_s must be a finite double column.");
end
compare_string(required_field(simulation, "solver", "output.simulation"), ...
    definition.solver, "output.simulation.solver");
compare_double(required_field(simulation, "fixed_step_s", "output.simulation"), ...
    definition.fixed_step_s, "output.simulation.fixed_step_s");
compare_double(time_s(end), definition.duration_s, "output.simulation.time_s(end)");

evaluation = require_struct(output, "evaluation", "output.evaluation");
evaluationFields = ["sample_start_s", "sample_end_s", "mean_packet_age_s", ...
    "omega_mean_packet_age", "rmse_zoh_m", "rmse_cv_m", "nrmse_zoh", ...
    "nrmse_cv", "max_error_zoh_m", "max_error_cv_m", ...
    "performance_ratio", "improvement_percent", "omega_delay", ...
    "omega_time_constant", "omega_sample_period"];
for name = evaluationFields
    value = required_field(evaluation, name, "output.evaluation");
    if ~(isa(value, "double") && isscalar(value) && isreal(value) && isfinite(value))
        error("teleopDelay:ExperimentCaseOutputInvalid", ...
            "output.evaluation.%s must be a finite double scalar.", name);
    end
end
compare_double(evaluation.omega_delay, ...
    definition.omega_rad_s * definition.delay_s, "output.evaluation.omega_delay");
compare_double(evaluation.omega_time_constant, ...
    definition.omega_rad_s * definition.time_constant_s, ...
    "output.evaluation.omega_time_constant");
compare_double(evaluation.omega_sample_period, ...
    definition.omega_rad_s * definition.sample_period_s, ...
    "output.evaluation.omega_sample_period");
compare_double(evaluation.omega_mean_packet_age, ...
    definition.omega_rad_s * evaluation.mean_packet_age_s, ...
    "output.evaluation.omega_mean_packet_age");
end

function value = require_struct(container, field, context)
value = required_field(container, field, context);
if ~isstruct(value) || ~isscalar(value)
    error("teleopDelay:ExperimentCaseOutputInvalid", ...
        "%s must be a scalar struct.", context + "." + field);
end
end

function value = required_field(container, field, context)
if ~isstruct(container) || ~isscalar(container) || ~isfield(container, char(field))
    error("teleopDelay:ExperimentCaseOutputMismatch", ...
        "%s.%s is missing from the successful case output.", context, field);
end
value = container.(char(field));
end

function compare_string(actual, expected, field)
if ~(isstring(actual) && isscalar(actual) && ~ismissing(actual)) || ...
        actual ~= string(expected)
    error("teleopDelay:ExperimentCaseOutputMismatch", ...
        "%s does not match the manifest case definition.", field);
end
end

function compare_integer(actual, expected, field)
if ~(isa(actual, "double") && isscalar(actual) && isreal(actual) && ...
        isfinite(actual) && actual == fix(actual) && actual == expected)
    error("teleopDelay:ExperimentCaseOutputMismatch", ...
        "%s does not exactly match the manifest case definition.", field);
end
end

function compare_double(actual, expected, field)
if ~(isa(actual, "double") && isscalar(actual) && isreal(actual) && ...
        isfinite(actual) && isa(expected, "double") && isscalar(expected) && ...
        isreal(expected) && isfinite(expected))
    error("teleopDelay:ExperimentCaseOutputMismatch", ...
        "%s is not a finite double scalar matching the manifest case definition.", field);
end
scale = max([1, abs(actual), abs(expected)]);
if abs(actual - expected) > eps(scale)
    error("teleopDelay:ExperimentCaseOutputMismatch", ...
        "%s does not match the manifest case definition at machine precision.", field);
end
end
